
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/mambo/Downloads/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.2.0-27-generic - x86_64
...
